更新 cron.yaml

diff --git a/.github/workflows/cron.yaml b/.github/workflows/cron.yaml
--- a/.github/workflows/cron.yaml
+++ b/.github/workflows/cron.yaml
@@ -1,23 +1,70 @@
-name: update wex.json
+name: 更新 cs
 
 on:
-  workflow_dispatch:  # 手动触发
+  push:
+    branches:
+      - wex
+  workflow_dispatch:
+  schedule:
+    - cron: '*/55 * * * *'
 
 jobs:
-  sync:
+  update-spider:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout current repo
-        uses: actions/checkout@v2
-        
-      - name: bash
+      # Step 1: Checkout the repository
+      - name: 检出代码库
+        uses: actions/checkout@v3
+
+      # Step 2: Setup Python
+      - name: 设置 Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.9'
+
+      # Step 3: Cache dependencies
+      - name: Cache Python dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
+
+      # Step 4: Install necessary dependencies
+      - name: 安装依赖
         run: |
-          cd ${{ github.workspace }}
-          file="niu.json"   #文件路径
-          curl -s http://www.饭太硬.com/jm/jiemi.php?url=http://tv.999888987.xyz >$file
-          id=0   #文件夹ID
-          token="94449a2b538ba6bb1cb44c4"
-          # file="bbbs.jpeg"
-          curl https://upload.kstore.space/upload/$id?access_token=$token -F "file=@$file"
-                  
+          python -m pip install --upgrade pip
+          python -m pip install requests jq
+
+          #  处理可能的依赖冲突,增加日志
+          python -m pip install --upgrade --force-reinstall requests jq > install_log.txt
+          cat install_log.txt
+
+      # Step 5: 获取、修改 Wex JSON 并上传
+      - name: 获取、修改 Wex JSON 并上传
+        run: |
+          # 获取 JSON 数据
+          NEW_JSON=$(curl -s https://9280.kstore.space/wex.json 2>/dev/null)
+
+          # 如果 NEW_JSON 为空，跳过后续操作, 并记录错误日志
+          if [[ -z "$NEW_JSON" ]]; then
+            echo "::error::Failed to fetch new JSON from kstore. Skipping update."
+            exit 1
+          fi
+
+          # 使用 jq 修改 JSON 数据并保存到 cs.json
+          echo "$NEW_JSON" | jq  '.sites |= map(
+            if .name == "公众号：王二小放牛娃" then .name = "推荐"
+            elif .name == "影视专用┃配置中心" then .name = "配置中心"
+            else .
+            end
+           ) | .lives = [] | .doh = [] | .sites =  del(.sites[] | select(.name == "⬇️【网盘类先扫码】⬇️"))' > cs.json
+
+          # 上传到 Kstore
+          curl -X POST \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ secrets.KSTORE_TOKEN }}" \
+            -d @cs.json \
+            "https://upload.kstore.dev/upload/${{ secrets.KSTORE_ID }}"
